spring.application.name=newsaggregator

server.port= 9090
# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:newsdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=user
spring.datasource.password=user@123

# Hibernate Config
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Logging SQL 
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# News API Configuration
newsapi.base-url=https://newsapi.org/v2/top-headlines
newsapi.api-key=a3e9a3a610084772862c1e05ee065cb7


#Spring Security
spring.security.user.name=Chaitanya
spring.security.user.password=test@26
